-- ============================================================
-- SNGEDU — Khôi phục 3 bảng lõi bị THIẾU trong project Supabase hiện tại:
-- subjects (môn học), chapters (chương), questions (câu hỏi trắc nghiệm).
--
-- Các bảng này được admin.js / index.js dùng ở rất nhiều chỗ nhưng KHÔNG
-- có migration nào tạo chúng trong repo — có lẽ ban đầu được tạo tay
-- trên Supabase Studio ở project cũ và không được export ra file .sql.
--
-- Chạy toàn bộ file này trong Supabase Dashboard > SQL Editor (project
-- qdecktzyiuxtupkxkfkw) MỘT LẦN DUY NHẤT.
-- ============================================================

-- 1) SUBJECTS (môn học) --------------------------------------------------
create table if not exists public.subjects (
  id               text primary key,               -- mã môn, ví dụ 'TOAN', do admin tự đặt (uppercase)
  name             text not null,
  order_no         int,
  status           text not null default 'ready',   -- ví dụ: ready / coming_soon / hidden...
  folder           text,                             -- nhóm/thư mục hiển thị (có thể null)
  show_explanation boolean not null default true,
  created_at       timestamptz not null default now()
);

alter table public.subjects enable row level security;

-- Ai cũng đọc được (trang chủ hiển thị danh sách môn học cho khách chưa đăng nhập)
drop policy if exists "subjects_select_public" on public.subjects;
create policy "subjects_select_public"
  on public.subjects for select
  using (true);

-- Chỉ admin được thêm/sửa/xoá
drop policy if exists "subjects_admin_write" on public.subjects;
create policy "subjects_admin_write"
  on public.subjects for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));


-- 2) CHAPTERS (chương trong từng môn) ------------------------------------
create table if not exists public.chapters (
  id          bigint generated by default as identity primary key,
  subject_id  text not null references public.subjects(id) on delete cascade,
  chapter     text not null,        -- mã chương (dùng để nối với questions.chapter)
  label       text not null,        -- tên hiển thị của chương
  note        text,
  group_name  text not null default 'Nội dung chính',  -- ví dụ: 'Nội dung chính' / 'Đề thi thử'
  order_no    int,
  created_at  timestamptz not null default now(),
  unique (subject_id, chapter)
);

alter table public.chapters enable row level security;

drop policy if exists "chapters_select_public" on public.chapters;
create policy "chapters_select_public"
  on public.chapters for select
  using (true);

drop policy if exists "chapters_admin_write" on public.chapters;
create policy "chapters_admin_write"
  on public.chapters for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));


-- 3) QUESTIONS (câu hỏi trắc nghiệm) --------------------------------------
create table if not exists public.questions (
  id           bigint generated by default as identity primary key,
  subject_id   text not null references public.subjects(id) on delete cascade,
  chapter      text not null,        -- khớp với chapters.chapter (cùng subject_id)
  content      text not null,
  options      jsonb not null,       -- mảng 4 đáp án, ví dụ ["A...","B...","C...","D..."]
  correct_idx  int not null,         -- chỉ số đáp án đúng (0-3)
  explanation  text,
  order_no     int,
  created_at   timestamptz not null default now()
);

create index if not exists idx_questions_subject_chapter
  on public.questions (subject_id, chapter);

alter table public.questions enable row level security;

drop policy if exists "questions_select_public" on public.questions;
create policy "questions_select_public"
  on public.questions for select
  using (true);

drop policy if exists "questions_admin_write" on public.questions;
create policy "questions_admin_write"
  on public.questions for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Báo cho PostgREST nạp lại schema ngay (thường tự động, chạy thêm cho chắc)
notify pgrst, 'reload schema';
